defaults:
  - _self_
  - dataset: default_dataset
  - evaluation_dataset: val_set_4 # toughest one out of 4 val sets
  - dataloader: default_dataloader
  - prompt : default_prompt
  - model: llama2
  - train: none_none_zero_shot_structured
  - eval: none_none_zero_shot_structured
  - tokenizer: llama2
  - quantization: quantization
  - generation: default_generation
  - parsing: default_parse

# using absolute paths here, need to change with rel paths at some point
distilled_dataset_sft_path: /work/dlclarge1/fernandr-thesis_workspace/bar-llama/dataset/seed_dataset/distilled_dataset.json
raw_dataset_sft_path: /work/dlclarge1/fernandr-thesis_workspace/bar-llama/dataset/seed_dataset/raw_dataset.json