defaults:
  - _self_
  - dataset: all_domains_all_samples
  - evaluation_dataset: test_set_1 # toughest one out of 4 val sets
  - dataloader: default_dataloader
  - prompt : markdown_answer_first_few_shot_unstructured
  - model: llama2
  - train: markdown_answer_first_few_shot_unstructured
  - eval: markdown_answer_first_few_shot_unstructured
  - tokenizer: llama2
  - quantization: quantization
  - generation: temp_06
  - parsing: markdown_answer_first_few_shot_unstructured
  - seeds : seed_314
  - inference_seeds : seed_206

# using absolute paths here, need to change with rel paths at some point
distilled_dataset_sft_path: /home/fr/fr_fr/fr_rf1031/bar-llama/dataset/seed_dataset/distilled_dataset.json
raw_dataset_sft_path: /home/fr/fr_fr/fr_rf1031/bar-llama/dataset/seed_dataset/raw_dataset.json